apiVersion: v1
kind: Pod
metadata:
  labels:
    run: licao-casa
    service: webserver
  name: licao-casa
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.2"
        memory: "64Mi"

  - image: portainer/portainer-ce
    name: portainer
    resources:
      limits:
        cpu: "1.5"
        memory: "256Mi"
      requests:
        cpu: "1"
        memory: "128Mi"
    ports:
    - containerPort: 9000

  - image: busybox
    name: busybox
    resources:
      limits:
        cpu: "0.3"
        memory: "128Mi"
      requests:
        cpu: "0.2"
        memory: "128Mi"
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
