apiVersion: v1
kind: Service # Tipo do objeto, no caso, um Service
metadata:
  name: svc-clusterip
spec:
  selector: # Seleciona os Pods que serão expostos pelo Service
    app: nginx # Neste caso, os Pods com o label app=nginx
  ports:
    - protocol: TCP
      port: 80 # Porta do Service
      name: http
      targetPort: 80 # Porta dos Pods
  type: ClusterIP # Tipo do Service    