apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: alertmanager-allow-external
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 9093