apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-prometheus-rule
  namespace: monitoring
  labels:
    prometheus: k8s # Label que indica que o PrometheusRule será utilizado pelo Prometheus do Kubernetes
    role: alert-rules # Label que indica que o PrometheusRule contém regras de alerta
    app.kubernetes.io/name: kube-prometheus # Label que indica que o PrometheusRule faz parte do kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus # Label que indica que o PrometheusRule faz parte do kube-prometheus
spec:
  groups:
  - name: nginx-prometheus-rule
    rules:
    - alert: NginxDown # Nome do alerta
      #expr: up{job="nginx"} == 0 # Expressão que será utilizada para disparar o alerta
      expr: nginx_up == 0 # Expressão que será utilizada para disparar o alerta
      for: 1m # Tempo que a expressão deve ser verdadeira para que o alerta seja disparado
      labels:
        severity: critical # Label que indica a severidade do alerta
      annotations:
        summary: "Nginx is down" # Título do alerta
        description: "Nginx is down for more than 1 minute. Pod name: {{ $labels.pod }}" # Descrição do alerta
    - alert: NginxHighRequestRate # Nome do alerta
      expr: rate(nginx_http_requests_total[5m]) > 10 # Expressão que será utilizada para disparar o alerta
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Nginx has high request rate" # Título do alerta
        description: "Nginx has high request rate for more than 1 minute. Pod name: {{ $labels.pod }}" # Descrição do alerta    