apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-exporter-daemonset 
  name: node-exporter-daemonset 
spec: 
  selector: 
    matchLabels: 
      app: node-exporter-daemonset
  template: 
    metadata: 
      labels: 
        app: node-exporter-daemonset
    spec:
      hostNetwork: true # Habilita o uso da rede do host, usar com cuidado
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest # Imagem do contêiner
        ports:
        - containerPort: 9100
          hostPort: 9100
        volumeMounts: # Lista de volumes que serão montados no contêiner, pois o node-exporter precisa de acesso ao /proc e /sys
        - name: proc # Nome do volume
          mountPath: /host/proc # Caminho onde o volume será montado no contêiner
          readOnly: true # Habilita o modo de leitura apenas
        - name: sys # Nome do volume 
          mountPath: /host/sys # Caminho onde o volume será montado no contêiner
          readOnly: true # Habilita o modo de leitura apenas
      volumes: # Lista de volumes que serão utilizados no Pod
      - name: proc # Nome do volume
        hostPath: # Tipo de volume 
          path: /proc # Caminho do volume no host
      - name: sys # Nome do volume
        hostPath: # Tipo de volume
          path: /sys # Caminho do volume no host