# Definição de um Deployment para o servidor Nginx
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  # replicas: 3             # Número inicial de réplicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.02      # Limite de CPU
            memory: 32Mi    # Limite de memória
          # requests:
          #   cpu: 250m        # Requisição de CPU
          #   memory: 128Mi    # Requisição de memória