apiVersion: kyverno.io/v1
kind: Policy #apenas para o namespace
metadata:
  name: ensure-images-from-trusted-repo
  namespace: exemplo
spec:
  validationFailureAction: Enforce
  rules:
  - name: trusted-repo-check
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Somente imagens do repo da Chainguard."
      pattern:
        spec:
          containers:
          - name: "*"
            image: "cgr.dev/chainguard/*"