apiVersion: v1
kind: Service # Tipo do objeto, no caso, um Service
metadata:
  name: meu-service-nodeport
spec:
  selector: # Seleciona os Pods que serão expostos pelo Service
    app: meu-app # Neste caso, os Pods com o label app=meu-app
  ports:
    - protocol: TCP
      port: 80 # Porta do Service
      name: http
      targetPort: 80 # Porta dos Pods
      nodePort: 32000 # Porta no nó onde o serviço estará acessível
  type: NodePort # Tipo do Service