apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector: 
    matchLabels:
      app: uptime-kuma
  strategy:
    type: Recreate #elimina todos os pods antigos antes de criar os novos 
  template: 
    metadata:
      labels:
        app: uptime-kuma
    spec:
      hostNetwork: true
      containers:
      - image: louislam/uptime-kuma:1
        name: uptime-kuma
        resources:
          limits:
            cpu: 2
            memory: 1024Mi
          requests:
            cpu: 1
            memory: 512Mi

        livenessProbe: # Checa se o contêiner está vivo
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10 # Tempo para iniciar a checagem após o contêiner iniciar
          periodSeconds: 10 # Frequência da checagem
          timeoutSeconds: 5 # Tempo máximo para a checagem responder
          failureThreshold: 3 # Número de falhas antes de considerar o contêiner como não saudável
        
        readinessProbe: # Checa se o contêiner está pronto para receber tráfego
          exec: # Usa um comando para checar se o contêiner está pronto
            command:
            - curl
            - -f
            - http://localhost:3001/
          initialDelaySeconds: 10 # Tempo para iniciar a checagem após o contêiner iniciar
          periodSeconds: 10 # Frequência da checagem
          timeoutSeconds: 5 # Tempo máximo para a checagem responder
          failureThreshold: 3 # Número de falhas antes de considerar o contêiner como não saudável
          successThreshold: 1 # Número de sucessos antes de considerar o contêiner como saudável
        
        startupProbe: # Checa se o contêiner iniciou corretamente
          tcpSocket: # Usa TCP para checar se o contêiner iniciou corretamente
            port: 3001
          initialDelaySeconds: 10 # Tempo para iniciar a checagem após o contêiner iniciar
          timeoutSeconds: 5 # Tempo máximo para a checagem responder
          failureThreshold: 5 # Número de falhas antes de considerar o contêiner como não saudável 
        